import 'dart:io';

void main(List<String> args) {
  final projectRoot = Directory.current.path;
  final lockFile = File(_join(projectRoot, 'pubspec.lock'));
  if (!lockFile.existsSync()) {
    stderr.writeln('pubspec.lock not found in $projectRoot');
    exit(1);
  }

  final lockLines = lockFile.readAsLinesSync();
  String? version;
  var inBlock = false;
  for (final line in lockLines) {
    if (line.startsWith('  font_awesome_flutter:')) {
      inBlock = true;
      continue;
    }
    if (inBlock) {
      if (line.startsWith('  ') && !line.startsWith('    ')) {
        break;
      }
      final trimmed = line.trimLeft();
      if (trimmed.startsWith('version:')) {
        final parts = trimmed.split('"');
        if (parts.length >= 2) {
          version = parts[1];
          break;
        }
      }
    }
  }
  if (version == null || version.isEmpty) {
    stderr.writeln('font_awesome_flutter version not found in pubspec.lock');
    exit(1);
  }
  final pubCache =
      Platform.environment['PUB_CACHE'] ??
      _join(Platform.environment['LOCALAPPDATA'] ?? '', 'Pub', 'Cache');
  if (pubCache.isEmpty) {
    stderr.writeln('PUB_CACHE/LOCALAPPDATA not set');
    exit(1);
  }

  final faPath = _join(
    pubCache,
    'hosted',
    'pub.dev',
    'font_awesome_flutter-$version',
    'lib',
    'font_awesome_flutter.dart',
  );
  final faFile = File(faPath);
  if (!faFile.existsSync()) {
    stderr.writeln('font_awesome_flutter.dart not found at $faPath');
    exit(1);
  }

  final lines = faFile.readAsLinesSync();
  final mapEntries = <String, String>{};

  final iconUrlReg =
      RegExp(r'https://fontawesome.com/icons/([^?]+)\?style=([a-z]+)');
  final iconConstReg = RegExp(r'static const IconData ([A-Za-z0-9_]+) = ');

  String? pendingIconName;
  String? pendingStyle;

  for (final line in lines) {
    final urlMatch = iconUrlReg.firstMatch(line);
    if (urlMatch != null) {
      pendingIconName = urlMatch.group(1);
      pendingStyle = urlMatch.group(2);
      continue;
    }

    final constMatch = iconConstReg.firstMatch(line);
    if (constMatch != null && pendingIconName != null && pendingStyle != null) {
      final fieldName = constMatch.group(1)!;
      final key = '$pendingStyle $pendingIconName';
      mapEntries.putIfAbsent(key, () => fieldName);
      pendingIconName = null;
      pendingStyle = null;
    }
  }

  if (mapEntries.isEmpty) {
    stderr.writeln('No icon mappings generated.');
    exit(1);
  }

  final outPath = _join(
    projectRoot,
    'lib',
    'utils',
    'font_awesome_name_mapping.dart',
  );

  final out = StringBuffer();
  out.writeln("import 'package:flutter/widgets.dart';");
  out.writeln("import 'package:font_awesome_flutter/font_awesome_flutter.dart';");
  out.writeln('');
  out.writeln('// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.');
  out.writeln('// Source: font_awesome_flutter $version');
  out.writeln('');
  out.writeln('/// Utility function to retrieve icons based on css classes.');
  out.writeln('/// Returns null if no icon matches.');
  out.writeln('IconData? getIconFromCss(String cssClasses) {');
  out.writeln('  const Map<String, String> cssStyles = {');
  out.writeln("    'far': 'regular', 'fas': 'solid', 'fab': 'brands',");
  out.writeln("    'fad': 'duotone', 'fal': 'light', 'fat': 'thin',");
  out.writeln('  };');
  out.writeln('');
  out.writeln('  final separated = cssClasses.split(RegExp(r"\\s+"));');
  out.writeln('  try {');
  out.writeln('    var style = separated.firstWhere(cssStyles.containsKey);');
  out.writeln('    style = cssStyles[style]!;');
  out.writeln('    var icon = separated.firstWhere((c) => c.startsWith(\'fa-\'));');
  out.writeln('    icon = icon.replaceFirst(\'fa-\', \'\');');
  out.writeln("    return faIconNameMapping['\$style \$icon'];");
  out.writeln('  } on StateError {');
  out.writeln('    return null;');
  out.writeln('  }');
  out.writeln('}');
  out.writeln('');
  out.writeln('/// Icon name to icon mapping for font awesome icons.');
  out.writeln('/// Keys are in the following format: "style iconName"');
  out.writeln('const Map<String, IconData> faIconNameMapping = {');

  for (final entry in mapEntries.entries) {
    out.writeln("  '${entry.key}': FontAwesomeIcons.${entry.value},");
  }

  out.writeln('};');

  File(outPath).writeAsStringSync(out.toString());
  stdout.writeln('Generated $outPath (${mapEntries.length} entries).');
}

String _join(String a, [String? b, String? c, String? d, String? e, String? f]) {
  final parts = <String?>[a, b, c, d, e, f].whereType<String>().toList();
  return parts.join(Platform.pathSeparator);
}
